env: merge-multi-agent-v0

env_args:
  seed: 0
  roll_out_n_steps: 100 
  #; [Hz]
  simulation_frequency : 15
  # time step
  duration : 20
  policy_frequency : 5
  COLLISION_REWARD : 200
  HIGH_SPEED_REWARD : 1
  HEADWAY_COST : 4
  HEADWAY_TIME : 1.2
  MERGING_LANE_COST : 4
  action_masking: False
  n_step: 8
  #  1: easy,  2: medium,  3: hard
  traffic_density : 2
  safety_guarantee: False

test_greedy: True
test_nepisode: 10
test_interval: 1000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 4050000
